### ISSUE TITLE
NPE in IntegrationOperation in version 4.0.1

### ISSUE THREAD

**Issue by ygnessin** [segmentio/analytics-android#400]
Hi, I just upgraded to version 4.0.1 with bundled integrations Flurry and Amplitude, both versions 1.0.0. I saw no errors while testing, but after rolling out my app update to production I saw the following crash come through Crashlytics in the wild:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.segment.analytics.ValueMap com.segment.analytics.ProjectSettings.trackingPlan()' on a null object reference
       at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:169)
       at com.segment.analytics.Analytics.performRun(Analytics.java:1025)
       at com.segment.analytics.Analytics$4$1.run(Analytics.java:258)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5725)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

My target SDK is 23 and my min SDK is 16. I am using ProGuard in my app (not sure if related) but am calling `-keep class com.segment.analytics.** { *; }` as dictated in your docs, as well as `-keep class com.flurry.sdk.* { *; }` for Flurry.

The crash has already occurred multiple times for multiple users, spanning various devices and OS versions. I hope you can fix soon, or at least let me know of a temporary workaround ASAP, otherwise I'll have to roll back my update and my segment integration. I would be happy to share any more details that may help you debug if necessary. Thank you very much!

**Comment by ygnessin** [comment]
This seems somewhat similar to the crashes reported in #395 and fixed in #396, in that the error stems from a null instance of `ProjectSettings`; in this case, when trying to fetch the tracking plan. Hopefully a similar solution can be implemented?

**Comment by f2prateek** [comment]
@ygnessin sorry about that, turns out #396 didn't quite fix the issue. If you have a reproducible case and can test out the snapshot release, that would be awesome so we can verify the patch indeed works.

**Comment by ygnessin** [comment]
@f2prateek sure - I've never used a snapshot release before in my gradle file, could you tell me how to configure Segment to use the snapshot version?

**Comment by f2prateek** [comment]
You can use the 4.0.2 version now, should be available in a few minutes.

**Comment by ygnessin** [comment]
Even though I did not have a reproducible test case, I re-packaged my app using 4.0.2 and it's now been in production for 24 hours without seeing a crash. Thanks for the quick fix!

**Comment by f2prateek** [comment]
@ygnessin Thanks for confirming!
