### ISSUE TITLE
Null pointer exception on ValueMap

### ISSUE THREAD

**Issue by adoankim** [segmentio/analytics-android#465]
Hello,

We're getting a lot of NullPointerException when calling identify of Analytics. The version we are using is the **4.1.6**

And the point where we get it:
```
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:821)
        at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:894)
        at com.segment.analytics.ValueMap.putAll(ValueMap.java:99)
        at com.segment.analytics.Analytics.identify(Analytics.java:400)
```

Did you already got some issue like this before?

Thanks!

**Comment by f2prateek** [comment]
Fixed here https://github.com/segmentio/analytics-android/pull/466.

In the meantime a fix would be to clean up your maps and not send `null` values.

**Comment by adoankim** [comment]
Thanks @f2prateek!

**Comment by adoankim** [comment]
@f2prateek  Ummm, i think that this does not solve our problem. Because is not the case.

The null pointer is caused by the identify line on the next code. Instead of maps we are using Analytics trait class. So we are not sending null in values parameter.

```
        Traits traits = new Traits();
        traits.putEmail(user.getEmail());
        try {
            analytics.identify(userId, traits, null);
        } catch(Exception e) {
            throw new IdentifyException(e);
        }
```

**Comment by f2prateek** [comment]
@adoankim can you send me a reproducible case?

For me, this failed (without #466 merged):

```java
analytics.identify(null, new Traits().putEmail(null), null);
```

But what you sent above works fine, (both before and after #466):

```java
analytics.identify(null, new Traits().putEmail("prateek@segment.com"), null);
```

Maybe `user.getEmail` is returning `null` in your code?

**Comment by adoankim** [comment]
@f2prateek sorry, i confirmed with the teammate that was working on the issue and is possible to get  a  new Traits().putEmail(null) in our case. I though that the think was  about sending something like:

`analytics.identify(userId, null, null);`

Thanks for the response!.

**Comment by f2prateek** [comment]
Thanks for confirming!
