### ISSUE TITLE
com.segment.analytics.internal.Utils.isEmptyOrBlank()

### ISSUE THREAD

**Issue by claudiogaalvao** [segmentio/analytics-android#798]
Using **release 4.10.0**, I faced this error:

LOCATION: Utils.java line 215 in com.segment.analytics.internal.Utils.isEmptyOrBlank()
EXCEPTION: java.lang.NullPointerException
MESSAGE: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

**Comment by wenxi-zeng** [comment]
@claudiogaalvao please post the full stacktrace so we can better understand the issue. also `4.10.0` does not compile google's new privacy policy. your app might in risk of getting unpublished from the store if you're targeting api level 29 or above. please consider upgrade to the latest release.

**Comment by claudiogaalvao** [comment]
Follow the stacktrace:

![image (3)](https://user-images.githubusercontent.com/38148114/162189899-936b2a19-5454-4291-8645-6f6ce4813ffc.png)

And thank you for the advice about the version @wenxi-zeng

**Comment by wenxi-zeng** [comment]
hey @claudiogaalvao the root cause [here](https://github.com/segmentio/analytics-android/blob/c98d430fae821744eaafe3ab56f949e431f584ac/analytics/src/main/java/com/segment/analytics/Analytics.java#L178) is that looks like you are using Analytics.with(...) which uses a registered singleton, and if it doesnt find a registered singleton it tries to create one using a writeKey from the android-string-resources [here](https://github.com/segmentio/analytics-android/blob/c98d430fae821744eaafe3ab56f949e431f584ac/analytics/src/main/java/com/segment/analytics/Analytics.java#L178), which is exactly whats being hit in the stack trace u have

> at com.segment.analytics.Analytics.with(Analytics.java:178)

so my suggestion here is to ensure that a singleton instance is registered via
`Analytics.setSingletonInstance(...)`

cc @prayansh

**Comment by wenxi-zeng** [comment]
@winghouchan the latest update to the amplitude integration addresses the new google privacy policy. failure to upgrade to the latest version will lead your app being unpublished from the store starting from August. **what you suggested is NOT a desirable workaround**. you probably want to upgrade to analytics-react-native 2, as 1.x will be deprecated soon. please open an issue on the react native repo for suggestions.

**Comment by winghouchan** [comment]
Understood, it is in our backlog to upgrade to 2.x. However in the meantime, breaking changes from sub-dependencies is more undesirable. Ideally, I think the Amplitude integration could put constraints on the version of analytics-android it depended on, published a new version and informed dependents that older versions were being deprecated because of updates to the new Google privacy policy as opposed to breaking dependents even though the August deadline has not been reached.

**Comment by martymiller** [comment]
Hi, my team is having this issue as well.  We started seeing crashes in Firebase after upgrading to 4.10.4.  Is there anything we can do in our code to prevent a crash or should we just wait for an update?

**Comment by wenxi-zeng** [comment]
@martymiller can you confirm if you're on analytics-android or analytics-react-native?

if you are on analytics-android, the workaround is to ensure that a singleton instance is registered via: `Analytics.setSingletonInstance(...)`

if you are on analytics-react-native, please open an issue on the [repo](https://github.com/segmentio/analytics-react-native). 

I'm also reporting this issue to our react native team, as we have received enough crash reports regarding to this issue.

**Comment by alanjcharles** [comment]
Hi @claudiogaalvao- this problem is corrected in the latest version of Analytics React Native. Since you are on version 1 you will ultimately need to migrate (it's easy).[ Here is the guide for that.](https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md) We currently do not have plans to release new versions of the 1.x architecture. Please feel free to reach out to friends@segment.com with questions or drop an issue on the Analytics React Native repo.

**Comment by martymiller** [comment]
> 

Thanks for the quick response! We are on analytics-android.  This is the code that is called when the application starts.  It's only called once. 

```
val analytics =
      Analytics.Builder(application.applicationContext, SEGMENT_API_KEY)
        .trackApplicationLifecycleEvents()
        .build()
Analytics.setSingletonInstance(analytics) 
```

**Comment by martymiller** [comment]
@alanjcharles I see you closed this ticket.  We are still having this issue on Android native.  We are not using React Native.  Unless there is an update that fixes this, the issue is not resolved.

**Comment by prayansh** [comment]
Hi @martymiller could you share the stacktrace of the crash?

**Comment by martymiller** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at com.segment.analytics.internal.Utils.isEmptyOrBlank(Utils.java:215)
       at com.segment.analytics.Analytics$Builder.<init>(Analytics.java:1101)
       at com.segment.analytics.Analytics.with(Analytics.java:178)
       at com.outdoorsy.analytics.SegmentAnalyticsManager.<init>(SegmentAnalyticsManager.kt:55)
       at com.outdoorsy.analytics.SegmentAnalyticsManager_Factory.newInstance(SegmentAnalyticsManager_Factory.java:35)
       at com.outdoorsy.analytics.SegmentAnalyticsManager_Factory.get(SegmentAnalyticsManager_Factory.java:27)
       at com.outdoorsy.analytics.SegmentAnalyticsManager_Factory.get(SegmentAnalyticsManager_Factory.java:11)
       at com.outdoorsy.api.interceptors.AuthorizationInterceptor_Factory.get(AuthorizationInterceptor_Factory.java:37)
       at com.outdoorsy.api.interceptors.AuthorizationInterceptor_Factory.get(AuthorizationInterceptor_Factory.java:13)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.outdoorsy.di.module.NetworkModule_ProvidesOkHttpClientFactory.get(NetworkModule_ProvidesOkHttpClientFactory.java:42)
       at com.outdoorsy.di.module.NetworkModule_ProvidesOkHttpClientFactory.get(NetworkModule_ProvidesOkHttpClientFactory.java:14)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.outdoorsy.di.module.NetworkModule_ProvidesBaseUrlClientFactory.get(NetworkModule_ProvidesBaseUrlClientFactory.java:47)
       at com.outdoorsy.di.module.NetworkModule_ProvidesBaseUrlClientFactory.get(NetworkModule_ProvidesBaseUrlClientFactory.java:16)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.outdoorsy.di.module.NetworkModule_ProvidesRetrofitBuilderFactory.get(NetworkModule_ProvidesRetrofitBuilderFactory.java:32)
       at com.outdoorsy.di.module.NetworkModule_ProvidesRetrofitBuilderFactory.get(NetworkModule_ProvidesRetrofitBuilderFactory.java:12)
       at com.outdoorsy.di.module.NetworkServicesModule_ProvidesStaticServiceFactory.get(NetworkServicesModule_ProvidesStaticServiceFactory.java:43)
       at com.outdoorsy.di.module.NetworkServicesModule_ProvidesStaticServiceFactory.get(NetworkServicesModule_ProvidesStaticServiceFactory.java:15)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.outdoorsy.repositories.AmenitiesRepository_Factory.get(AmenitiesRepository_Factory.java:32)
       at com.outdoorsy.repositories.AmenitiesRepository_Factory.get(AmenitiesRepository_Factory.java:12)
       at com.outdoorsy.workers.StaticDataWorker_AssistedFactory.create(StaticDataWorker_AssistedFactory.java:30)
       at com.outdoorsy.di.worker.DaggerWorkerFactory.createWorker(DaggerWorkerFactory.kt:26)
       at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
       at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
       at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```
we are on the latest version of the Android SDK

**Comment by prayansh** [comment]
Hey @martymiller!
```
at com.segment.analytics.internal.Utils.isEmptyOrBlank(Utils.java:215)
at com.segment.analytics.Analytics$Builder.<init>(Analytics.java:1101)
at com.segment.analytics.Analytics.with(Analytics.java:178)
```
Looks like its hitting [this codepath](https://github.com/segmentio/analytics-android/blob/4.10.4/analytics/src/main/java/com/segment/analytics/Analytics.java#L178), which is executed only when `singleton == null`.

So I am guessing that the `anonymousUserId` is being computed before the singleton is being initialized thus causing this issue. If this is the case then I would recommend keeping track of your own singleton, rather than relying on `Analytics.with(...)` which tries to initialize an analytics instance using some defaults and writeKey from the android-string-resources [here](https://github.com/segmentio/analytics-android/blob/4.10.4/analytics/src/main/java/com/segment/analytics/Analytics.java#L177)

**Comment by wenxi-zeng** [comment]
@martymiller a side note: since you're using kotlin, consider to upgrade to our all new [analytics-kotlin](https://github.com/segmentio/analytics-kotlin) to take the full advantage of a coroutine-based sdk. the performance is 3x better than analytics-android. see here for [performance report](https://segment.com/blog/sdk-performance-improvements/).

**Comment by martymiller** [comment]
Thanks @wenxi-zeng and @prayansh For the suggestions.  I'm managing the singleton myself now using Dagger, so we'll see how this goes.  I'd like to upgrade to the Kotlin version soon, but it looks like certain things need to be updated in the code.  Properties and Traits are no longer recognized, so I'm getting compilation errors.  Does the Kotlin version address the "Google Play warning" issue?
